### ISSUE TITLE
Generate a jazzy.yaml file

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#123]
We need to generate a jazzy.yaml config file to permit generation of docs from the Swift docstrings. See: 
https://azure.github.io/azure-sdk/ios_documentation.html#swift-docstrings

ping @bsiegel as he did most of the docs generation for `azure-sdk-for-ios`

**Comment by bsiegel** [comment]
Yep, check out https://github.com/Azure/azure-sdk-for-ios/tree/master/.jazzy and https://github.com/Azure/azure-sdk-for-ios/blob/master/Scripts/build_api_docs.sh
