### ISSUE TITLE
os.log not available on WSL

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#140]
Autorest.swift won't run on WSL due to the use of OSX-specific os.log. Instead, we should evaluate using:
https://github.com/apple/swift-log

This is intended for use with cross-platform tools.

**Comment by tjprescott** [comment]
@sacheu is this still an issue since we use StdoutLogger?

**Comment by sacheu** [comment]
Yes, we now use StdoutLogger. we can close this issue.
