### ISSUE TITLE
Support Swift API View

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#141]
Since we are building a code model and generating code, we should attempt to parse the AST for the generated code and generate the necessary artifacts to produce a Swift API View. A potentially useful library for this would be:
https://github.com/yanagiba/swift-ast

Another potentially useful library:
https://github.com/apple/swift-syntax

For the necessary format, see:
https://gist.github.com/pakrym/09558b6a339449ab1c26a7f95e6df37c

The tokens can be uploaded to: `apivew.dev`

The generator code should live here: https://github.com/Azure/azure-sdk-tools/tree/master/src

(Python is located here: https://github.com/Azure/azure-sdk-tools/tree/main/packages/python-packages/api-stub-generator)

APIView: https://apiview.dev/

**Comment by sacheu** [comment]
@tjprescott ,can you please help me understand what is the difference between 'Swift API view' and the Jazzy generated doc?

**Comment by tjprescott** [comment]
@sacheu Swift API View is a much more concise version of the API. The arch board considers the documentation too verbose, and you have to click to expand things, which is tedious. Also, they don't want to see any documentation because their philosophy is that the API should be self-documenting. You should be able to read the signature and know what it does. So API view is a very stripped down version to help facilitate their review.

**Comment by tjprescott** [comment]
This may also be helpful:
https://swift-ast-explorer.com/

**Comment by tjprescott** [comment]
This has been completed.
