### ISSUE TITLE
Conditionally create code for apiversion

### ISSUE THREAD

**Issue by sacheu** [Azure/autorest.swift#192]
The latest generated AzureCommunicationChat client did not generate the API version field correctly:

```swift
     /// API version of the  to invoke. Defaults to the latest.
     public enum ApiVersion: String {
        /// API version ""
        case v = ""
 
         /// The most recent API version of the
         public static var latest: ApiVersion {
            return .v
         }
     }

```

Should be:
```swift
     /// API version of the  to invoke. Defaults to the latest.
     public enum ApiVersion: String {
        /// API version "2020-09-21-preview2"
        case v20200921preview2 = "2020-09-21-preview2"
 
         /// The most recent API version of the
         public static var latest: ApiVersion {
            return .v20200921preview2
         }
     }
```

We need to:

- [ ] Fix the generation of ApiVersion enum when specified in Swagger
- [ ] Do not generate the ApiVersion enum if apiVersion is not specified in Swagger
- [ ] Write a simple Swagger to test both cases and add that to our test suite. It might make sense to put this test Swagger in the testserver.

**Comment by tjprescott** [comment]
Since apiVersion is required by the ClientOptions protocol, we will leave this as-is.
