### ISSUE TITLE
Generated enum case has difficulty with certain keywords

### ISSUE THREAD

**Issue by JoshuaLai** [Azure/autorest.swift#299]
![Screen Shot 2021-02-05 at 1 18 52 PM](https://user-images.githubusercontent.com/9044372/107073032-b178ae00-679b-11eb-8825-5c8763440a7a.png)

As per screenshot. The enum cases generated from autorest doesn't seem to add the ` `` ` around keywords such as `public`.

**Comment by tjprescott** [comment]
Fixed by #300.
