### ISSUE TITLE
Enable CheckEnforcer

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#303]
https://github.com/Azure/azure-sdk-tools/tree/master/tools/check-enforcer

This is enabled for the AzureSDK repo. It should be enabled here as well to ensure that all required checks (i.e. the build pipeline) are successful in order to merge.

**Comment by mitchdenny** [comment]
If you only have one pipeline then you can make that pipeline required. Check Enforcer addresses a specific concern where you have multiple pipelines that MAY run, but no single one of them can be mandatory. Regardless, this is where you set the branch protection rules which make a particular check mandatory (using the Python repo for Azure SDK as an example):

![image](https://user-images.githubusercontent.com/513398/108122701-cee13c80-70f8-11eb-83cf-0bf53f79c2c5.png)

Before Check Enforcer will show up to mark as mandatory you need to install it into the repo:

https://github.com/apps/check-enforcer

And create a configuration file at ```eng/CHECKENFORCER``` similar to [this](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/CHECKENFORCER).

**Comment by tjprescott** [comment]
Thanks @mitchdenny for the info! I updated the settings and it is working as intended. Closing this issue.
