### ISSUE TITLE
Compilation error: AnyCodable.swift not found

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#317]
Schema.swift line 89 shows that "AnyCodable" is generated as the swift type for `Any`. However, `AnyCodable.swift` was intended to be an internal file only, so this breaks. We either need to copy the file into the generated files or find some other representation for this.

**Comment by tjprescott** [comment]
As a temporary workaround, the `AnyCodable.swift` file can be copied manually into the source (outside the Generated folder), which should resolve the compilation errors.

**Comment by tjprescott** [comment]
@PotterDai when you generate code, you will likely get a compilation error that type `Any` doesn't conform to `RequestStringConvertible`. Internally, Autorest will map the swagger "any" type to the `AnyObject` Swift type, which will not conform to the necessary protocol, so it may actually create more headache for you than when it was "broken". It will certainly require custom code.

**Comment by PotterDai** [comment]
@tjprescott  What would be the down side if we include AnyCodable.swift file as part of the generated code?
