### ISSUE TITLE
dash should not go to property of enum

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/autorest.swift#7]
"Azure-AsyncOperation" and ["Retry-After"](https://github.com/Azure/autorest.testserver/blob/master/swagger/lro.json#L342)  becomes property:
```swift
public var Azure-AsyncOperation: String?
public var Retry-After: Int32?
```

```swift
enum CodingKeys: String, CodingKey {
        case Azure-AsyncOperation = "Azure-AsyncOperation"
        case Location = "Location"
        case Retry-After = "Retry-After"
}
```
and makes Swift unhappy.
... and breaks **Lower Camel Case** naming convention.

**Comment by tjprescott** [comment]
Closing as we do not intend to continue investment in the C# code generator.
